name: tech0-gen8-step4-pos-app-78
runtime: PYTHON|3.12
env:
  - name: DATABASE_URL
    value: mysql://user:sakepara2025@pos-db.mysql.database.azure.com:3306/pos_db
  - name: ALLOWED_ORIGINS
    value: https://tech0-gen8-step4-pos-app-77.azurewebsites.net 