-- 文字コード設定を追加
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- 商品マスタテーブルの作成
CREATE TABLE IF NOT EXISTS 商品マスタ (
    PRD_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CODE CHAR(13) UNIQUE,
    NAME VARCHAR(50),
    PRICE INTEGER
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 取引テーブルの作成
CREATE TABLE IF NOT EXISTS 取引 (
    TRD_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATETIME TIMESTAMP,
    EMP_CD CHAR(10),
    STORE_CD CHAR(5),
    POS_NO CHAR(3),
    TOTAL_AMT INTEGER
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 取引明細テーブルの作成
CREATE TABLE IF NOT EXISTS 取引明細 (
    TRD_ID INTEGER,
    DTL_ID INTEGER,
    PRD_ID INTEGER,
    PRD_CODE CHAR(13),
    PRD_NAME VARCHAR(50),
    PRD_PRICE INTEGER,
    PRIMARY KEY (TRD_ID, DTL_ID),
    FOREIGN KEY (TRD_ID) REFERENCES 取引(TRD_ID),
    FOREIGN KEY (PRD_ID) REFERENCES 商品マスタ(PRD_ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- サンプルデータの挿入
INSERT INTO 商品マスタ (CODE, NAME, PRICE) VALUES
('1234567890123', 'ソフラン', 300),
('2345678901234', 'タイガー缶ブラン', 200),
('3456789012345', '福島産ほうれん草', 188),
('4567890123456', '四ツ谷サイダー', 160); 