name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: tech0gen8step4acr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tech0gen8step4acr.azurecr.io/pos-backend:latest
          file: ./Dockerfile
          context: .
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen8-step4-pos-app-78'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'tech0gen8step4acr.azurecr.io/pos-backend:latest' 