name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push container image
      run: |
        cd SP14/backend
        docker build -f Dockerfile.production -t ghcr.io/${{ github.repository_owner }}/pos-backend:${{ github.sha }} .
        docker push ghcr.io/${{ github.repository_owner }}/pos-backend:${{ github.sha }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tech0-gen8-step4-pos-app-78'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/${{ github.repository_owner }}/pos-backend:${{ github.sha }}' 